serverAddr = "121.43.149.18"
serverPort = 7000
#natHoleStunServer="stun.easyvoip.com:3478"
#natHoleStunServer="stun.voipstunt.com:3478"
natHoleStunServer="stun.cheapvoip.com:3478"

[[proxies]]
name = "p2p_ssh"
type = "xtcp"
secretKey = "abcdefg"
localIP = "127.0.0.1"
localPort = 22